#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
# You can press :h SpaceVim-config to see all config
# Or You can see ~/.SpaceVim/autoload/SpaceVim.vim to see source code config
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    relativenumber = 0
    colorscheme = "jellybeans"
    #colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    # vimcompatible = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "smart"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#xml"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#vue"

[[layers]]
name = "lang#c"

[[layers]]
name = "format"

[[layers]]
name = "colorscheme"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#groovy"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#java"
# if local jdk version >= 16, need to change jar -jar flag
java_formatter_jar = "~/.SpaceVim.d/java_formatter.jar"
format_on_save = true

[[layers]]
name = "lsp"
filetypes = [
  "go"
]
#[layers.override_cmd]
#java = [
#"java",
#"-Declipse.application=org.eclipse.jdt.ls.core.id1",
#"-Dosgi.bundles.defaultStartLevel=4",
#"-Declipse.product=org.eclipse.jdt.ls.core.product",
#"-Dlog.protocol=true",
#"-Dlog.level=NONE",
#"-noverify",
#"-Xmx1G",
#"-jar",
#"/home/tinyan/Documents/jdt-language-server-latest/plugins/org.eclipse.equinox.launcher_1.5.400.v20190515-0925.jar",
#"-configuration",
#"/home/tinyan/Documents/jdt-language-server-latest/config_linux",
#"-data",
#"/home/tinyan/.cache/javalsp"
#]

[[layers]]
name = "checkers"

[[layers]]
name = "core#banner"

[[layers]]
name = "ui"
  enable_indentline = true
